koopjs/koop-core

src/index.js, src/middleware/index.js, test/index-test.js, test/middleware-test.js
ArcGIS Pro adds preceding whitespace to the `orderByFields` parameter when adding a Koop service, which causes a parse error.  This pull request prevents the parse error by trimming request params that are of type `String`.
=> Trim leading/trailing whitespace on request params that arrive as strings

CHANGELOG.md, src/helpers/index.js, src/index.js, test/helpers-test.js
* Added helper module and function to create route paths with decoration based on passed options
* Added ability to insert the provider-specifc route fragment into the route path (rather then simple prefixing), by replacing occurrence of `$provider$`substring
* Added ability to skip decoration of route with namespace and provider info altogether.  This allows routes to be added that are not provider-specific (see https://github.com/koopjs/koop-output-geoservices/pull/6)
=> Helper function to compose route paths

CHANGELOG.md, package.json, src/helpers/index.js, src/index.js, test/helpers-test.js
Rework of route-compostion helper function.  For plugins routes, it looks for placeholders `$namespace$` and `$providerParams$` in the defined `route.path` and replaces them.  If not present, defaults to former prefixing pattern `namespace/:host/:id`.  Also handles case where only one of `$namespace$` or `$providerParams$` are found; if `$namespace$` is found, but `$providerParams$` is not, the provider params are added directly after the namespace. If `$providerParams$` is found, but `$namespace$` is not, the provider namespace is prefixed to the route (assumes that namespace should always precede provider params).
=> Route helper

CHANGELOG.md, package.json, src/helpers/index.js, src/index.js, test/helpers-test.js, test/index-test.js
If a route contains the `$namespace` placeholder, but no `$providerParams` placeholder, `:host/:id` are omitted by default, regardless of the provider's `hosts` and `disableIdParam` property-values.  This is important for special-case routes like `$namespace/rest/info` which currently are being constructed like `namespace/:host/:id/rest/info`.
=> Prevent addition of :host/:id to routes with $namespace but no $providerParams

CHANGELOG.md, package.json, src/index.js
Rework `authenticationSpecification` on Model prototype.  Mixes-in provider name to auth-spec object.
=> Rework `authenticationSpecification` on Model prototype

CHANGELOG.md, src/helpers/index.js, test/helpers-test.js
When provider had `disableIdParam: true` routes were still being built as `/:host/:id/FeatureServer/:layer/:method`.  This PR corrects that.
=> Fix route construction where disbleIdParam = true

CHANGELOG.md, src/index.js
Looks like we have a bug in generic plugin registration.  See issue https://github.com/koopjs/koop-core/issues/50;  This PR makes the adjustment to remedy.
=> Make name-check throw error on undefined.

test/dataset-test.js, test/fixtures/fake-auth/index.js, test/fixtures/fake-provider-ii/index.js, test/fixtures/fake-provider-ii/models/fake.js, test/index-test.js
Add tests and fixtures to test that the auth-plugin can be applied to providers selectively - by registering providers _after_ the auth-plugin.
=> Auth options

CHANGELOG.md, src/helpers/index.js, src/index.js, test/helpers-test.js, test/index-test.js
This PR adds an `options` parameter to provider registration.  If the options object contains a property named `routePrefix`, it's string value will be prepended to all provider route paths.
Documentation of this new option is required in koop docs.
=> Add route-prefix option to provider registration.

CHANGELOG.md, src/index.js
support for passing in an object of configuration or connection options when registering a new Cache provider.
Example using Koop-Redis:
```
const redisOptions = {
host: {
host: 'koop-sdmx.redis.cache.windows.net',
port: 6380,
auth_pass: 'SuperSecretAuth',
tls: { servername: 'koop-sdmx.redis.cache.windows.net' }
}
};
koop.register(redisCache, redisOptions);
```
=> support options when registering a cache

src/index.js, test/index-test.js
This PR fixes an existing bug caused by the changes to koop-output-geoservices [v1.2.0](https://github.com/koopjs/koop-output-geoservices/releases/tag/v1.2.0).  That release added a second set of routes with the `/rest/services` fragment and and placeholder for provider's `host` and `id` parameters, which need special handling to be properly bound to controllers.  Here, I change the functions that bind routes to the datasets controller so that it is compatible with current generation koop-output-geoservices.
=> Fix feature-server route paths for cached datasets

CHANGELOG.md, package.json, src/index.js
Added some organization/pretty printing of registered routes to the console output.  Each provider has two sets of routes: a set of optional "custom" routes that are defined in a provider's `routes.js` file, and a set of routes for each registered output-plugin.  See screengrab below:
=> Pretty printing of provider/plugin routes to terminal

CHANGELOG.md, package.json, src/index.js, test/index-test.js
This PR adds compression to all Koop routes by default, unless explicitly disabled with a config property called `disableCompression`.  Koop usage docs need to be updated to explain this.
=> Add compression by default, but allow it to be disabled

CHANGELOG.md, src/index.js, test/index-test.js
Preferentially use `config` argument for assignment of `this.config`.  If argument is `undefined`, use `config` module by default.
=> Use config arg for koop.config

CHANGELOG.md, src/index.js
* Bind plugin-routes first, then bind provider routes.
* Change the table header text for the console-printed route tables.
=> Fix order of route binding

CHANGELOG.md, src/models/index.js
Minor change to append the layer ID number to the end of the cache key.
=> Provide unique cache keys for each provider layer.

src/index.js, test/index-test.js, test/middleware-test.js
Change order of route binding; provider routes first, then plugin routes.  This allows custom routes on provider to supersede any similarly named routes defined by plugins.  This is a beneficial feature because it allows a provider author to add routes with an output-plugin signature that may not yet be supported by the plugin. For example, koop-output-geoservices does not yet support an `addFeatures` method/route.  But a provider could define such a route, e.g., `/provider/:id/FeatureServer/:layer/addFeatures`.  By binding this route first, we ensure that requests don't get sent to the `koop-output-geoservices` regexed route, i.e., `/provider/:id/FeatureServer/:layer/:method`.
=> Bind provider routes first.

src/index.js, test/index-test.js
A cleaner pattern for attaching the options object to a Model instance. Current pattern passes the `koop` instance to the Model constructor as the `options` argument.  Rationale for that is unclear.
This PR:
* changes that pattern so that the `options` object that arrives during registration is passed into the Model constructor.
* uses the `options.cache` preferentially
* merges the `options` and `koop` objects before passing into the Model constructor.  This is done to preserve backwards compatibility for any providers that are expecting the `koop` object to get passed into the constructor
=> Refactor attachment of options to provider Models.

CHANGELOG.md, src/index.js, src/models/index.js, test/index-test.js, test/model-test.js
This PR:
1. adds _transformation_ functions to the Koop data flow.
* A `before` function is fired before the the Model's `getData` and allows the modification of the `request` object.
* An `after` function is fired after the Model's `getData` function and allows modification of the data payload as well as further modification of the `request` object.
Transformation function will allow user to leverage published providers with custom manipulation without having to fork the original provider code.  For example, a user could use the Github provider to access datasets in non-WGS84 coordinate systems, but have the `after` function reproject the data to WGS84 before sending it on to koop-core.
2. preferentially uses the `name` option from provider registration for the provider routes.  This …
=> Add "before", "after" and "name" options.

CHANGELOG.md, src/index.js, test/index-test.js
The new `name` option was not being preferentially used in plugin route definition.  Fixed here.
=> Ensure provider option 'name' is used in routes.

src/helpers/register-plugin-routes.js, src/helpers/register-provider-routes.js, test/helpers/register-plugin-routes.spec.js, test/helpers/register-provider-routes.spec.js
Found a bug is the way registered routes are track in the route-map objects; this didn't affect functionality, just the console output that prints route-paths and methods.
=> Fix bug in tracking of registered routes.

CHANGELOG.md, src/models/extended-model.js
Prevent overwriting cache and option assignments that occur in provider model constructors
=> Patch model registration

CHANGELOG.md, src/helpers/register-plugin-routes.js, src/index.js, test/index-test.js
When a provider is registered, a provider's custom routes are registered first, followed by provider-namespaced output routes.  This ordering means that in the event of any route path collisions, the provider's custom routes will be used. This is intentional and was introduced in resposne to https://github.com/koopjs/koop-core/issues/88.
Some implementations may want or require the opposite, i.e., output routes registered first.  This PR adds a new provider registration option `defaultToOutputRoutes` which allows output routes to be registered first.  In the event of collisions, the output route is given precedence over the provider custom route.  The default value of this new option is `false`.
=> Add route precedence option.

CHANGELOG.md, index.js, lib/datasets/index.js, lib/helpers/namespaced-route-path.js, test/datasets/index.spec.js
1. Move datasets provider to its own directory
2. Use register function for datasets
3. fix bug in route construction when no `host` or `id` params
=> Move datasets provider to its own directory

lib/provider-registration/create-model.js, test/fixtures/fake-provider-ii/models/fake.js, test/fixtures/fake-provider/models/fake.js, test/provider-registration/create-model.spec.js, test/provider-registration/index.spec.js, test/provider-registration/provider-output-route.spec.js, test/provider-registration/provider-route.spec.js
This PR refactors the Model's "pull" method as an async function so that the nested callback are eliminated.
=> Refactor the Model pull method

CHANGELOG.md, lib/provider-registration/create-model.js, test/provider-registration/create-model.spec.js
Adds support for provider plugins using NodeJS streams instead of JSON to pass data to the output plugins (issue https://github.com/koopjs/koop-core/issues/141).
Caching doesn't make sense in this case, so the `pullStream` method is quite simple.
=> Add streaming support

CHANGELOG.md, lib/provider-registration/create-model.js, test/provider-registration/create-model.spec.js
Does not really make sense to have an `after` transform function in the case of a stream, as it it used to transform the geojson while in memory.  As it was not working (missing an await), this is not actually a breaking change.
=> Remove "after" option for pullStream.

index.js
This was done to prevent issues with the proxies AGOL use.  During item creation the correct token will be sent in the url query but not in the body.  The middleware that appends all body parameters to the query then overwrites the correct token with the incorrect token preventing the add item process from working correctly.
=> changed middleware to prefer query token
